### ISSUE TITLE
How to realize "Take the most significant 16 bits"

### ISSUE THREAD

**Issue by Mountain03** [andysworkshop/usb-microphone#5]
Thanks for your project which gave me a lot of help,but there is one point I dont understand;

int16_t sample = (data_in[0] & 0xfffffffe) | (rand() & 1);

How can this" take the most significant 16 bits and respect the sign bit" ?
I think this can only take the lower 16 bits without sign bit. 
thanks

**Comment by andysworkshop** [comment]
Hi, the short answer is that it's because the DMA peripheral reverses the word order in memory. The long answer is given in one of the comments on the article in my website.
